### ISSUE TITLE
Idea: Integration with OpenDAL to extend the storage backend to all storage services.

### ISSUE THREAD

**Issue by Xuanwo** [sjtug/rsync-sjtug#1]
Nice project!

Maybe we can work together to integrate opendal and extend the storage backend to all storage services? I think there are many people looking for solutions for rsync to different storage platforms.

**Comment by PhotonQuantum** [comment]
Thank you for the suggestion! I'm interested in adopting OpenDAL, but I have a few concerns that I'd like to address before doing so.

1. Does OpenDAL provide all the interfaces we need? e.g., listing by prefix, batch file deletion, object metadata (Content-Type, Content-Disposition), and, if possible, a mock interface.
2. This is more like a "meta" problem. What's the target user base? Currently, SJTUG is the only user of this project. In other words, who will benefit from the OpenDAL integration?
    File metadata is stored in a Redis server rather than a storage layer, i.e. files on the storage can't be addressed directly (they are content-addressable by their blake2b hash), only through a gateway. This makes the usage of this tool quite limited. Also, an existing HTTP service backed by the storage is required. See https://github.com/sjtug/rsync-sjtug#example.

**Comment by Xuanwo** [comment]
> Does OpenDAL provide all the interfaces we need? e.g., listing by prefix, batch file deletion, object metadata (Content-Type, Content-Disposition), and, if possible, a mock interface.

- [x] listing by prefix
- [x] batch file deletion: via https://github.com/datafuselabs/opendal/issues/1279 which expected to be released this week.
- [x] object metadata: `Content-Disposition` is missing, should be fixed via https://github.com/datafuselabs/opendal/issues/1346
- [x] mock interface: can be implemented via [Layer](https://opendal.databend.rs/opendal/raw/trait.Layer.html) or [Accessor](https://opendal.databend.rs/opendal/raw/trait.Accessor.html)

> who will benefit from the OpenDAL integration?

Good question! I think OpenDAL will benefit this project even in the current limited scope:

- Simplify implementation: we don't have to play with the verbose SDK API.
- Provides powerful [layers](https://opendal.databend.rs/opendal/layers/index.html):
  - retry: retry failed requests, e.g. read object from failed position automatically.
  - logging/tracing/metrics: Use when we need observability.

**Comment by PhotonQuantum** [comment]
Looks good! We can start working on it as soon as all the required methods are implemented. I look forward to working with you on the integration!

**Comment by PhotonQuantum** [comment]
All required ops are supported by OpenDAL now! I would like to confirm whether you are still interested in integrating OpenDAL into this project.

**Comment by PhotonQuantum** [comment]
Switched to OpenDAL in v0.4.x 🤩
